import BreadCrumb from '@/components/BreadCrumb'
import { Anton, Anton_SC, Inter } from 'next/font/google'
import Image from 'next/image'
import React from 'react'
import Link from 'next/link'
import Head from 'next/head'

const anton = Anton({ subsets: ['latin'], weight: ['400'], style: ['normal'] })
const antonSC = Anton_SC({ subsets: ['latin'], weight: ['400'], style: ['normal'] })
const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '600', '800'], style: ['normal'] })

const AiGeneratedArticle = () => {
    return (
        <>
            <Head>
                <title>AI-Generated Article Policy | Indian Journal of Physical Therapy</title>
                <meta charset="utf-8"></meta>
                <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0" />

                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name='keywords' content='IJOPT, Indian Journal of Physical Therapy, Indian Journal of Physiotherapy, Open Access Journal, Physiotherapy Journal, Physical Therapy Journal, International Journal for Physiotherapy, PhysioZine, AI-Generated Article Policy IJOPT' />
                <meta name="description" content="Indian Journal of Physical Therapy (IJOPT): Your trusted source for peer-reviewed articles, latest research, and expert insights in physiotherapy, Open access Journal. Explore now!" />

                <meta property="og:title" content="AI-Generated Article Policy of IJOPT" />
                <meta property="og:description" content="Indian Journal of Physical Therapy (IJOPT): Your trusted source for peer-reviewed articles, latest research, and expert insights in physiotherapy, Open access Journal. Explore now!" />
                <meta property="og:url" content="https://ijopt.co.in/policy/ai-generated-policy" />
                <meta property="og:image" content="/favicon.ico" />
                <meta property="og:type" content="website" />

                <link rel="icon" href="/favicon.ico" />
                <link rel="manifest" href="/manifest.json" />

                {/* <!-- Author and Publisher Meta Tags --> */}
                <meta name="author" content="Indian Journal of Physical Therapy" />
                <meta name="publisher" content="Indian Journal of Physical Therapy" />

                {/* Structured Data SEO */}
                <script type="application/ld+json">
                    {JSON.stringify({
                        "@context": "https://schema.org",
                        "@type": "Organization",
                        "name": "Indian Journal of Physical Therapy",
                        "url": "https://ijopt.co.in/policy/ai-generated-policy",
                        "logo": "https://ijopt.co.in/favicon.ico",
                        "description": "Indian Journal of Physical Therapy (IJOPT): Your trusted source for peer-reviewed articles, latest research, and expert insights in physiotherapy, Open access Journal. Explore now!",
                        "keywords": ["Physiotherapy Journal", "Open Access", "Research Articles", "Physical Therapy", "AI-Generated Article Policy of IJOPT"],
                    })}
                </script>
            </Head>
            <section className='author-tools-section'>
                <div className='container inner-content'>
                    <BreadCrumb basePath={['/', '/privacy-policy']} title='AI-Generated Article Policy | Indian Journal of Physical Therapy' />

                    <h1 className='section-title'>AI-Generated Article Policy</h1>
                    <hr className='mt-0' />

                    <p className={inter?.className}>
                        The Indian Journal of Physical Therapy (IJOPT) upholds the highest standards of academic integrity and ethical research practices. As part of our commitment to publishing original, evidence-based, and scientifically rigorous research, <strong>IJOPT does not accept research articles that are generated by artificial intelligence (AI)</strong>.
                    </p>

                    <div className={inter?.className}>
                        <p>
                            Authors submitting manuscripts to IJOPT must ensure that their work is the result of <strong>genuine human intellectual effort</strong>, including but not limited to study conception, data collection, analysis, and interpretation. While AI-based tools such as language models, grammar checkers, and reference managers may be used to assist in manuscript preparation, IJOPT strictly prohibits the submission of any research that is fully or partially generated by AI without proper human oversight and intellectual contribution.
                        </p>
                        <p>
                            IJOPT does not accept manuscripts where AI has been used to generate research data, results, methodologies, or entire sections of the manuscript, such as abstracts, discussions, and conclusions, without human verification and intellectual involvement.
                        </p>
                        <p>
                            All listed authors must take full responsibility for the originality, accuracy, and ethical integrity of the content they submit. The use of AI for minor editorial enhancements (e.g., grammar corrections, citation formatting) must be disclosed in the manuscript’s acknowledgment section. However, AI tools cannot be credited as authors or co-authors.
                        </p>
                        <p>
                            Any manuscript found to contain AI-generated content without proper human validation and intellectual input will be <strong>rejected outright</strong>. If such violations are discovered after publication, the article may be <strong>retracted</strong> from IJOPT, and the authors may be subject to a submission ban.
                        </p>
                        <p>
                            During the submission process, authors must provide a declaration confirming that AI-generated content has not been used to produce research findings, conclusions, or any critical analysis within the manuscript. The editorial team reserves the right to request additional clarifications or supporting documentation to verify compliance with this policy.
                        </p>
                        <p>
                            All submissions undergo rigorous editorial and peer-review processes, including <strong>AI-detection checks</strong> where necessary. If any manuscript is suspected of being AI-generated or lacking substantial human intellectual contribution, it will be <strong>rejected immediately</strong> without further review.
                        </p>
                        <p>
                            If an author is found violating this policy, their submission will be removed from consideration. In cases of repeated violations, the author may face a <strong>temporary or permanent submission ban</strong> from IJOPT. Institutions and funding bodies may also be notified in cases of serious ethical misconduct.
                        </p>
                        <p>
                            IJOPT encourages researchers to uphold ethical publishing standards and contribute original, high-quality research to the field of physical therapy. Any queries regarding AI usage in manuscript preparation should be directed to <strong>editor.ijopt@gmail.com</strong> for clarification before submission.
                        </p>
                        <p>
                            By submitting a manuscript to IJOPT, authors <strong>agree to comply</strong> with this AI-Generated Article Policy.
                        </p>
                    </div>
                </div>
            </section>
        </>
    )
}

export default AiGeneratedArticle